function [n_branch, Bus_no_xx, ii_indx_n, zz_mat, Vs, Bus_phases, phases_xx] = inference_data(n_branch, Phases)

          zz_mat = load('zz_mat.mat');                                     % zz_mat = BCBV*BIBC .......................
  %n_branch = size(struct2table(mpc.Branch),1);                             % number of branches .................
 Bus_nomat = ones(3,n_branch).*(2:n_branch+1);
 Bus_no_xx = reshape(Bus_nomat,[],1);                                      % ceate a vector with buses times three each bus except slack bus.........

 [ ii_indx_n, ~ ] = find(Phases);                                          % present phases at each bus ...............

Vs = [ (1.02 + 1i*0);  (1.02*cos(-2.0944) + 1.02i*sin(-2.0944)); ...       % reference Voltage Vs.........
      (1.02*cos(2.0944) + 1.02i*sin(2.0944)) ];                            
 Bus_phases = Bus_no_xx(ii_indx_n);                                        % list of all buses with their corresponding present phases except slack..........
  phases_xx = Phases(ii_indx_n);                                           % list of all present phases except slack..................

end