%% Observability at the previous time step tk1 ...............

function [Volt_Bus_tk1, Bus_power_tk1] = obser_t1k(ii_indx_n)

 Volt_Bus_tk1 = load('Volt_Bus_tk1');                                      % data of V(t_k) ..........................
 Volt_Bus_tk1 = Volt_Bus_tk1.Volt_Bus_tk1;

    Power_tk1 = load('Power_tk1');                                         % data of S(t_k) ......................
Bus_power_tk1 = Power_tk1.Power_tk1(ii_indx_n);                            % S(t_k) corresponding to all the buses/present phases......

end